spring:
  resources:
    static-locations: classpath:/static/
  profiles:
    #开发环境，相当于优先引用application-dev.yml
    active: dev

    #浏览器中项目url时，需要添加#（e.g：http://localhost:8088/#/index1）
#  mvc:
#    static-path-pattern: /#/**

  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    #(e.g:比如你修改了一个文件，已经update到tomcat，但刷新页面还是之前的页面，就是因为缓存引起的。)
    cache: false
    prefix: classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
#关闭热部署
  devtools:
    restart:
      enabled: false

#配置redis
  redis:
    host: 192.168.59.100
    port: 6379
    password:
    pool:
      max-active: 8 ## 设置最大连接数，0为无限

#mybatis的配置
mybatis:
  type-aliases-package: com.mode.springboot.entity
  mapper-locations: classpath:mapping/*.xml
#pageHelper配置（官网推荐配置）
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

server:
  #  配置端口号，https默认端口号为443，改为8443端口
  port: 8088
  #  配置ssl证书
#  ssl:
    #    SSL证书springboot.keystore与application.yml放在同级目录下
#    key-store: classpath:springboot.keystore
#    key-store-password: 123456
#    keyStoreType: JKS
#    keyAlias: tomcat




